### ISSUE TITLE
Error fetching status for ***: no resources found for

### ISSUE THREAD

**Issue by baymax55** [lyc8503/AliyunCertRenew#1]
赋予权限后无法获取资源

<img width="1201" alt="image" src="https://github.com/user-attachments/assets/a98aebbc-675f-4bcd-aafc-9d847244943c">

AliyunCertRenew version 71cae54
time="2024-09-02T09:11:16Z" level=info msg="AliyunCertRenew starting..."
time="2024-09-02T09:[11](https://github.com/baymax55/AliyunCertRenew/actions/runs/10664143495/job/29555152102#step:5:12):16Z" level=info msg="Domains to check: [***]"
time="2024-09-02T09:11:16Z" level=info msg=">>> Checking ***"
time="2024-09-02T09:11:17Z" level=error msg="Error fetching status for ***: no resources found for ***"

**Comment by lyc8503** [comment]
你阿里云目前有正在使用这张证书的资源吗, 你这张免费证书是用在哪里? 没有对应云资源的话就会这样报错.

**Comment by baymax55** [comment]
> 你阿里云目前有正在使用这张证书的资源吗, 你这张免费证书是用在哪里? 没有对应云资源的话就会这样报错.

刚仔细看了下文档，好像是我申请的证书，自己手动部署的ssl，没有使用阿里云部署，应该是这个原因
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/e57feb48-9aa0-495f-9260-a28fb6248382">

**Comment by lyc8503** [comment]
嗯, 手动部署的 SSL 不能适用, 毕竟证书已经签发了, 没法在不重新部署的情况下续期.

如果你用的是 ECS 之类的独立服务器, 配置 ACME 自动申请证书会方便很多.

**Comment by baymax55** [comment]
请问我点了云服务器部署方式部署了ssl，可以使用这个脚本没，目前还是显示无法获取到该资源
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/d42d0899-977c-4dfb-a03a-c2926bd171ab">
<img width="878" alt="image" src="https://github.com/user-attachments/assets/dbab4708-3122-4f81-8de2-a02034938835">

**Comment by baymax55** [comment]
显示获取不到任何资源，请问 是不是我的权限设置有问题呢
<img width="988" alt="image" src="https://github.com/user-attachments/assets/9a2de4d3-6391-4e10-baf3-00d9cb4a971d">

**Comment by lyc8503** [comment]
抱歉, 阿里云的云产品部署和多云部署所用的 API 完全不是同一套, 目前只支持阿里云云产品的. (比如 CDN, DCDN, 函数计算)

**Comment by baymax55** [comment]
> 抱歉, 阿里云的云产品部署和多云部署所用的 API 完全不是同一套, 目前只支持阿里云云产品的. (比如 CDN, DCDN, 函数计算)

谢谢🙏
